### ISSUE TITLE
Can no longer generate for different domain

### ISSUE THREAD

**Issue by neocryptek** [CheneyLin/codeSuperGenPass_ChromeExtension#1]
Hi,

The new visual update appears to have removed the previous feature of changing the domain in the generator dialog. I used to use this on websites that use different domains for their homepage and login pages, or old logins for sites that have now changed domains, or just generate the password for a domain without having to be navigated to it (ex: useful for logging into banks from aggregator websites like Mint), etc. Right now it seems whenever I change the domain information, it just reverts to the current domain when I de-focus the domain input box. Is there a reason this was changed to be read-only?

Thanks!

**Comment by CheneyLin** [comment]
In my computer, domain input box will delete subdomain prefix when it de-focus. I can change the domain and generate password.
Can you post extension version and chrome version, and full url of Mint, I will check it again.
Keep touch.

**Comment by CheneyLin** [comment]
I found some code maybe occur this error, I will update and release new version 3.0.1 to fix it.
Thank you.
